services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./User-Service
    container_name: user-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
