services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"

  user-service:
    build: ./User-Service
    container_name: user-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  task-service:
    build: ./Task-Service
    container_name: task-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo_data:
